export function regKeyExists(root: string,key: string): Promise<boolean>;
export function regListAllSubkeys(root: string,key: string): Promise<string[]>;
export function regListAllValues(root: string,key: string): Promise<string[]>;
export function regQueryValueType(root: string,key: string,name: string): Promise<string>;
export function regQueryStringValue(root: string,key: string,name: string): Promise<string | null>;
export function regQueryMultiStringValue(root: string,key: string,name: string): Promise<string[] | null>;
export function regQueryStringValueAndExpand(root: string,key: string,name: string): Promise<string | null>;
export function regQueryBinaryValue(root: string,key: string,name: string): Promise<Buffer | null>;
export function regQueryIntegerValue(root: string,key: string,name: string): Promise<number | bigint | null>;
export function regWriteKey(root: string,key: string): Promise<void>;
export function regWriteStringValue(root: string,key: string,name: string,value: string): Promise<void>;
export function regWriteMultiStringValue(root: string,key: string,name: string,value: string[]): Promise<void>;
export function regWriteExpandStringValue(root: string,key: string,name: string,value: string): Promise<void>;
export function regWriteBinaryValue(root: string,key: string,name: string,value: Buffer): Promise<void>;
export function regWriteDwordValue(root: string,key: string,name: string,value: number | bigint): Promise<void>;
export function regWriteQwordValue(root: string,key: string,name: string,value: number | bigint): Promise<void>;
export function regDeleteKeyValue(root: string,key: string,name: string): Promise<void>;
export function regDeleteKey(root: string,key: string): Promise<void>;
export function regExportKey(root: string,key: string,option?: object): Promise<object>;
export function regImportKey(root: string,key: string,data: object, option?: object): Promise<void>;
export function regDeleteKeyIncludingSubkeys(root: string,key: string): Promise<void>;